#!/bin/sh /etc/rc.common

START=50

reload()
{
    start
}

restart()
{
    reload
}

start()
{
    /usr/lib/sqm/run.sh start
}

stop()
{
    /usr/lib/sqm/run.sh stop
}

boot()
{
    # We are being run through hotplug scripts, don't do anything at boot
    logger -t SQM -s "sqm-scripts do nothing at boot, waiting for hotplug events."
    return 0
}
