#!/bin/sh

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
#       Copyright (C) 2012-4 Michael D. Taht, Toke Høiland-Jørgensen, Sebastian Moeller

# allow passing in the IFACE as first command line argument

[ -n "$IFACE" ] || exit 1

. /etc/sqm/sqm.conf
. ${SQM_LIB_DIR}/functions.sh
. ${SQM_LIB_DIR}/qdisc_funcs.sh
. ${SQM_LIB_DIR}/legacy_funcs.sh
. ${SQM_LIB_DIR}/defaults.sh

if [ ! -f "${SQM_STATE_DIR}/${IFACE}.state" ] ; then
    sqm_error "State file does not exists; SQM was not running on interface ${IFACE}"
    exit 1
fi
STATE_FILE="${SQM_STATE_DIR}/${IFACE}.state"

sqm_trace; sqm_trace "$(date): Stopping." # Add some space and a date stamp to verbose log output and log files to separate runs
sqm_log "Stopping SQM on ${IFACE}"

# make sure to only delete the ifb associated with the current interface
CUR_IFB=$( get_ifb_associated_with_if ${IFACE} )
[ -z "$CUR_IFB" ] && CUR_IFB=$( ifb_name ${IFACE} )

if [ -n "${SCRIPT}" ]; then
    if [ -f "${SQM_LIB_DIR}/$SCRIPT" ]; then
        sqm_log "Using custom SQM script: ${SCRIPT}"
        . "${SQM_LIB_DIR}/$SCRIPT"
    elif is_legacy_script "${SCRIPT}"; then
        sqm_warn "Legacy script ${SCRIPT} is deprecated and should not be used."
        sqm_warn "Using built-in sqm_stop() to shut down SQM"
    else
        sqm_error "Custom SQM script ${SCRIPT} not found!"
        exit 1
    fi
fi

sqm_stop
rm -f "${STATE_FILE}"

exit 0
